services:
  llm_guard_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AUTH_TOKEN=e5b469a03dfac1d1796ca14df2fb284af1f1ce1dab5f200fe99571498918caa9
      - LOG_LEVEL=INFO
      - APP_WORKERS=1
    volumes:
      - ./config/scanners.yml:/home/user/app/config/scanners.yml
